/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DueDiligenceRouteImport } from './routes/due-diligence'
import { Route as FollowUpsRouteImport } from './routes/follow-ups'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ImportRouteImport } from './routes/import'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as AdminGeographyRouteImport } from './routes/admin.geography'
import { Route as AdminProgramsRouteImport } from './routes/admin.programs'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as LeadsLeadIdRouteImport } from './routes/leads.$leadId'
import { Route as LeadsNewRouteImport } from './routes/leads.new'
import { Route as LettersIndexRouteImport } from './routes/letters.index'
import { Route as LettersGenerateRouteImport } from './routes/letters.generate'
import { Route as PartnersNetworkRouteImport } from './routes/partners.network'
import { Route as TerritoryIndexRouteImport } from './routes/territory.index'
import { Route as TerritoryCapacityRouteImport } from './routes/territory.capacity'
import { Route as TerritoryHeatmapRouteImport } from './routes/territory.heatmap'
import { Route as TerritoryMapRouteImport } from './routes/territory.map'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DueDiligenceRoute = DueDiligenceRouteImport.update({
  id: '/due-diligence',
  path: '/due-diligence',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpsRoute = FollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGeographyRoute = AdminGeographyRouteImport.update({
  id: '/admin/geography',
  path: '/admin/geography',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProgramsRoute = AdminProgramsRouteImport.update({
  id: '/admin/programs',
  path: '/admin/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsNewRoute = LeadsNewRouteImport.update({
  id: '/leads/new',
  path: '/leads/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LettersIndexRoute = LettersIndexRouteImport.update({
  id: '/letters/',
  path: '/letters/',
  getParentRoute: () => rootRouteImport,
} as any)
const LettersGenerateRoute = LettersGenerateRouteImport.update({
  id: '/letters/generate',
  path: '/letters/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersNetworkRoute = PartnersNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => PartnersRoute,
} as any)
const TerritoryIndexRoute = TerritoryIndexRouteImport.update({
  id: '/territory/',
  path: '/territory/',
  getParentRoute: () => rootRouteImport,
} as any)
const TerritoryCapacityRoute = TerritoryCapacityRouteImport.update({
  id: '/territory/capacity',
  path: '/territory/capacity',
  getParentRoute: () => rootRouteImport,
} as any)
const TerritoryHeatmapRoute = TerritoryHeatmapRouteImport.update({
  id: '/territory/heatmap',
  path: '/territory/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const TerritoryMapRoute = TerritoryMapRouteImport.update({
  id: '/territory/map',
  path: '/territory/map',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/due-diligence': typeof DueDiligenceRoute
  '/follow-ups': typeof FollowUpsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/partners': typeof PartnersRouteWithChildren
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/verification': typeof VerificationRoute
  '/admin/geography': typeof AdminGeographyRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/leads/new': typeof LeadsNewRoute
  '/letters/generate': typeof LettersGenerateRoute
  '/partners/network': typeof PartnersNetworkRoute
  '/territory/capacity': typeof TerritoryCapacityRoute
  '/territory/heatmap': typeof TerritoryHeatmapRoute
  '/territory/map': typeof TerritoryMapRoute
  '/leads/': typeof LeadsIndexRoute
  '/letters/': typeof LettersIndexRoute
  '/territory/': typeof TerritoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/due-diligence': typeof DueDiligenceRoute
  '/follow-ups': typeof FollowUpsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/partners': typeof PartnersRouteWithChildren
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/verification': typeof VerificationRoute
  '/admin/geography': typeof AdminGeographyRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/leads/new': typeof LeadsNewRoute
  '/letters/generate': typeof LettersGenerateRoute
  '/partners/network': typeof PartnersNetworkRoute
  '/territory/capacity': typeof TerritoryCapacityRoute
  '/territory/heatmap': typeof TerritoryHeatmapRoute
  '/territory/map': typeof TerritoryMapRoute
  '/leads': typeof LeadsIndexRoute
  '/letters': typeof LettersIndexRoute
  '/territory': typeof TerritoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/due-diligence': typeof DueDiligenceRoute
  '/follow-ups': typeof FollowUpsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/partners': typeof PartnersRouteWithChildren
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/verification': typeof VerificationRoute
  '/admin/geography': typeof AdminGeographyRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/leads/new': typeof LeadsNewRoute
  '/letters/generate': typeof LettersGenerateRoute
  '/partners/network': typeof PartnersNetworkRoute
  '/territory/capacity': typeof TerritoryCapacityRoute
  '/territory/heatmap': typeof TerritoryHeatmapRoute
  '/territory/map': typeof TerritoryMapRoute
  '/leads/': typeof LeadsIndexRoute
  '/letters/': typeof LettersIndexRoute
  '/territory/': typeof TerritoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/audit'
    | '/dashboard'
    | '/due-diligence'
    | '/follow-ups'
    | '/forgot-password'
    | '/import'
    | '/login'
    | '/notifications'
    | '/partners'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/verification'
    | '/admin/geography'
    | '/admin/programs'
    | '/admin/roles'
    | '/admin/users'
    | '/leads/$leadId'
    | '/leads/new'
    | '/letters/generate'
    | '/partners/network'
    | '/territory/capacity'
    | '/territory/heatmap'
    | '/territory/map'
    | '/leads/'
    | '/letters/'
    | '/territory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/audit'
    | '/dashboard'
    | '/due-diligence'
    | '/follow-ups'
    | '/forgot-password'
    | '/import'
    | '/login'
    | '/notifications'
    | '/partners'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/verification'
    | '/admin/geography'
    | '/admin/programs'
    | '/admin/roles'
    | '/admin/users'
    | '/leads/$leadId'
    | '/leads/new'
    | '/letters/generate'
    | '/partners/network'
    | '/territory/capacity'
    | '/territory/heatmap'
    | '/territory/map'
    | '/leads'
    | '/letters'
    | '/territory'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/audit'
    | '/dashboard'
    | '/due-diligence'
    | '/follow-ups'
    | '/forgot-password'
    | '/import'
    | '/login'
    | '/notifications'
    | '/partners'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/verification'
    | '/admin/geography'
    | '/admin/programs'
    | '/admin/roles'
    | '/admin/users'
    | '/leads/$leadId'
    | '/leads/new'
    | '/letters/generate'
    | '/partners/network'
    | '/territory/capacity'
    | '/territory/heatmap'
    | '/territory/map'
    | '/leads/'
    | '/letters/'
    | '/territory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuditRoute: typeof AuditRoute
  DashboardRoute: typeof DashboardRoute
  DueDiligenceRoute: typeof DueDiligenceRoute
  FollowUpsRoute: typeof FollowUpsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ImportRoute: typeof ImportRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PartnersRoute: typeof PartnersRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  VerificationRoute: typeof VerificationRoute
  AdminGeographyRoute: typeof AdminGeographyRoute
  AdminProgramsRoute: typeof AdminProgramsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  LeadsLeadIdRoute: typeof LeadsLeadIdRoute
  LeadsNewRoute: typeof LeadsNewRoute
  LettersGenerateRoute: typeof LettersGenerateRoute
  TerritoryCapacityRoute: typeof TerritoryCapacityRoute
  TerritoryHeatmapRoute: typeof TerritoryHeatmapRoute
  TerritoryMapRoute: typeof TerritoryMapRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
  LettersIndexRoute: typeof LettersIndexRoute
  TerritoryIndexRoute: typeof TerritoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/due-diligence': {
      id: '/due-diligence'
      path: '/due-diligence'
      fullPath: '/due-diligence'
      preLoaderRoute: typeof DueDiligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-ups': {
      id: '/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof FollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/geography': {
      id: '/admin/geography'
      path: '/admin/geography'
      fullPath: '/admin/geography'
      preLoaderRoute: typeof AdminGeographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/programs': {
      id: '/admin/programs'
      path: '/admin/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AdminProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/new': {
      id: '/leads/new'
      path: '/leads/new'
      fullPath: '/leads/new'
      preLoaderRoute: typeof LeadsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letters/': {
      id: '/letters/'
      path: '/letters'
      fullPath: '/letters/'
      preLoaderRoute: typeof LettersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letters/generate': {
      id: '/letters/generate'
      path: '/letters/generate'
      fullPath: '/letters/generate'
      preLoaderRoute: typeof LettersGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/network': {
      id: '/partners/network'
      path: '/network'
      fullPath: '/partners/network'
      preLoaderRoute: typeof PartnersNetworkRouteImport
      parentRoute: typeof PartnersRoute
    }
    '/territory/': {
      id: '/territory/'
      path: '/territory'
      fullPath: '/territory/'
      preLoaderRoute: typeof TerritoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/territory/capacity': {
      id: '/territory/capacity'
      path: '/territory/capacity'
      fullPath: '/territory/capacity'
      preLoaderRoute: typeof TerritoryCapacityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/territory/heatmap': {
      id: '/territory/heatmap'
      path: '/territory/heatmap'
      fullPath: '/territory/heatmap'
      preLoaderRoute: typeof TerritoryHeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/territory/map': {
      id: '/territory/map'
      path: '/territory/map'
      fullPath: '/territory/map'
      preLoaderRoute: typeof TerritoryMapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PartnersRouteChildren {
  PartnersNetworkRoute: typeof PartnersNetworkRoute
}

const PartnersRouteChildren: PartnersRouteChildren = {
  PartnersNetworkRoute: PartnersNetworkRoute,
}

const PartnersRouteWithChildren = PartnersRoute._addFileChildren(
  PartnersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuditRoute: AuditRoute,
  DashboardRoute: DashboardRoute,
  DueDiligenceRoute: DueDiligenceRoute,
  FollowUpsRoute: FollowUpsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ImportRoute: ImportRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PartnersRoute: PartnersRouteWithChildren,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  VerificationRoute: VerificationRoute,
  AdminGeographyRoute: AdminGeographyRoute,
  AdminProgramsRoute: AdminProgramsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminUsersRoute: AdminUsersRoute,
  LeadsLeadIdRoute: LeadsLeadIdRoute,
  LeadsNewRoute: LeadsNewRoute,
  LettersGenerateRoute: LettersGenerateRoute,
  TerritoryCapacityRoute: TerritoryCapacityRoute,
  TerritoryHeatmapRoute: TerritoryHeatmapRoute,
  TerritoryMapRoute: TerritoryMapRoute,
  LeadsIndexRoute: LeadsIndexRoute,
  LettersIndexRoute: LettersIndexRoute,
  TerritoryIndexRoute: TerritoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
